/**
 * Auto-generated by scripts/build-rnnoise-wasm.mjs — do not edit.
 * Placeholder: run `node scripts/build-rnnoise-wasm.mjs` with Emscripten to
 * produce the real artifact.
 */
export const RNNOISE_WASM_B64 = '';
