/**
 * RNNoise WASM processor and frame-adaptation ring.
 *
 * Loads the RNNoise WASM module from a checked-in base-64 artifact,
 * verifies its SHA-256 checksum, and provides:
 *   - `loadRnnoise()` — lazy module loader with checksum verification
 *   - `RnnoiseInstance` — per-track WASM state wrapper
 *   - `RnnoiseRing` — 480-sample frame-adaptation ring buffer
 *
 * The WASM module processes audio at 48 kHz mono in 480-sample (10 ms) frames.
 */

const FRAME_SIZE = 480;

/** Error thrown when the WASM module fails to load or verify. */
export class RnnoiseLoadError extends Error {
	constructor(message: string) {
		super(message);
		this.name = 'RnnoiseLoadError';
	}
}

/** Wraps a single RNNoise WASM denoiser instance. */
export interface RnnoiseInstance {
	/** Process one 480-sample mono frame. Returns VAD probability (unused). */
	processFrame(input: Float32Array, output: Float32Array): number;
	destroy(): void;
}

interface RnnoiseModule {
	instance: WebAssembly.Instance;
	memory: WebAssembly.Memory;
	create(): number;
	processFrame(state: number, out: number, inp: number): number;
	destroy(state: number): number;
}

let moduleCache: Promise<RnnoiseModule> | null = null;

/**
 * Load the RNNoise WASM module from the checked-in base-64, verify checksum.
 * The module is loaded lazily (only when first called); a module-level cache
 * prevents re-instantiation.
 */
export async function loadRnnoise(): Promise<{ createInstance(): RnnoiseInstance }> {
	if (!moduleCache) {
		moduleCache = loadRnnoiseModule();
	}
	const mod = await moduleCache;
	return {
		createInstance(): RnnoiseInstance {
			return createRnnoiseInstance(mod);
		},
	};
}

async function loadRnnoiseModule(): Promise<RnnoiseModule> {
	// Dynamic import to avoid bundling the base-64 in the main chunk.
	// The base-64 file is auto-generated by scripts/build-rnnoise-wasm.mjs.
	let b64: string;
	let manifest: { sizeBytes: number; checksum: string };
	try {
		const b64Mod = await import('./rnnoise-wasm-b64');
		b64 = b64Mod.RNNOISE_WASM_B64;
		const manifestMod = await import('./rnnoise-wasm-manifest.json', {
			with: { type: 'json' },
		});
		manifest = (manifestMod as { default: { sizeBytes: number; checksum: string } }).default;
	} catch (err) {
		throw new RnnoiseLoadError(
			`Failed to load RNNoise WASM assets: ${err instanceof Error ? err.message : String(err)}`
		);
	}

	// Decode base-64
	const binary = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));

	// Verify byte size
	if (binary.length !== manifest.sizeBytes) {
		throw new RnnoiseLoadError(
			`RNNoise WASM size mismatch: expected ${manifest.sizeBytes} bytes, got ${binary.length}`
		);
	}

	// Verify SHA-256 checksum
	const hashBuffer = await crypto.subtle.digest('SHA-256', binary);
	const hashHex = Array.from(new Uint8Array(hashBuffer))
		.map((b) => b.toString(16).padStart(2, '0'))
		.join('');
	const expected = manifest.checksum.replace('sha256-', '');
	if (hashHex !== expected) {
		throw new RnnoiseLoadError(
			`RNNoise WASM checksum mismatch: expected sha256-${expected}, got sha256-${hashHex}`
		);
	}

	// Instantiate
	const wasmModule = await WebAssembly.compile(binary);
	const memory = new WebAssembly.Memory({ initial: 256, maximum: 256 });
	const imports = { env: { memory } };
	const instance = await WebAssembly.instantiate(wasmModule, imports);
	const exports = instance.exports as unknown as Record<string, WebAssembly.ExportValue>;

	const create = exports['rnnoise_create'] as () => number;
	const processFrame = exports['rnnoise_process_frame'] as (
		state: number,
		out: number,
		inp: number,
	) => number;
	const destroy = exports['rnnoise_destroy'] as (state: number) => number;

	if (!create || !processFrame || !destroy) {
		throw new RnnoiseLoadError('RNNoise WASM missing required exports');
	}

	return { instance, memory, create, processFrame, destroy };
}

function createRnnoiseInstance(mod: RnnoiseModule): RnnoiseInstance {
	const statePtr = mod.create();
	if (!statePtr) {
		throw new RnnoiseLoadError('rnnoise_create returned null');
	}

	// Allocate two 480-float regions in the WASM heap (input + output)
	const allocSize = FRAME_SIZE * 4 * 2; // both input and output frames
	const inPtr = mod.instance.exports['malloc']
		? (mod.instance.exports['malloc'] as (size: number) => number)(allocSize)
		: statePtr + 1024; // fallback: offset from state
	const outPtr = inPtr + FRAME_SIZE * 4;

	let destroyed = false;

	return {
		processFrame(input: Float32Array, output: Float32Array): number {
			if (destroyed) throw new Error('RnnoiseInstance already destroyed');
			// Copy input into WASM heap
			const heapF32 = new Float32Array(mod.memory.buffer, inPtr, FRAME_SIZE);
			heapF32.set(input.subarray(0, FRAME_SIZE));
			// Process
			const vad = mod.processFrame(statePtr, outPtr, inPtr);
			// Copy output from WASM heap
			const outHeap = new Float32Array(mod.memory.buffer, outPtr, FRAME_SIZE);
			output.set(outHeap);
			return vad;
		},
		destroy(): void {
			if (!destroyed) {
				destroyed = true;
				mod.destroy(statePtr);
				// Free the allocated I/O buffers
				if (mod.instance.exports['free']) {
					(mod.instance.exports['free'] as (ptr: number) => void)(inPtr);
				}
			}
		},
	};
}

/**
 * Frame-adaptation ring: buffers input chunks until 480 samples are available,
 * then calls processFrame and emits 480 samples. Processes ALL complete
 * 480-sample frames in a single push() call to prevent accumulator growth
 * when input blocks are larger than 480 samples (e.g. 1024-sample export
 * blocks). Stateful.
 */
export class RnnoiseRing {
	private readonly instance: RnnoiseInstance;
	private accumulator: Float32Array;
	private accLen = 0;

	constructor(instance: RnnoiseInstance) {
		this.instance = instance;
		this.accumulator = new Float32Array(FRAME_SIZE * 2); // room for partial + new
	}

	/**
	 * Push a mono block of any size. Returns all denoised 480-sample frames
	 * produced (may be empty, 480, 960, etc. samples).
	 * Caller must not modify the returned buffer.
	 */
	push(input: Float32Array): Float32Array {
		// Append input to accumulator
		const totalLen = this.accLen + input.length;
		if (totalLen > this.accumulator.length) {
			const grown = new Float32Array(totalLen + FRAME_SIZE);
			grown.set(this.accumulator.subarray(0, this.accLen));
			this.accumulator = grown;
		}
		this.accumulator.set(input, this.accLen);
		this.accLen = totalLen;

		// Process all complete 480-sample frames
		const outputParts: Float32Array[] = [];
		while (this.accLen >= FRAME_SIZE) {
			const frameIn = this.accumulator.subarray(0, FRAME_SIZE);
			const frameOut = new Float32Array(FRAME_SIZE);
			this.instance.processFrame(frameIn, frameOut);
			outputParts.push(frameOut);

			// Shift remaining samples to front
			this.accLen -= FRAME_SIZE;
			if (this.accLen > 0) {
				this.accumulator.copyWithin(0, FRAME_SIZE, FRAME_SIZE + this.accLen);
			}
		}

		if (outputParts.length === 0) return new Float32Array(0);
		if (outputParts.length === 1) return outputParts[0];

		// Concatenate all output frames
		const totalOutput = outputParts.length * FRAME_SIZE;
		const result = new Float32Array(totalOutput);
		for (let i = 0; i < outputParts.length; i++) {
			result.set(outputParts[i], i * FRAME_SIZE);
		}
		return result;
	}

	/** Drain remaining buffered samples (call at end of stream). */
	drain(): Float32Array {
		if (this.accLen === 0) return new Float32Array(0);
		// Zero-pad to 480
		const padded = new Float32Array(FRAME_SIZE);
		padded.set(this.accumulator.subarray(0, this.accLen));
		this.accLen = 0;
		const output = new Float32Array(FRAME_SIZE);
		this.instance.processFrame(padded, output);
		return output;
	}
}
